### ISSUE TITLE
Error handling shouldn't hide exceptions when interacting with CKAN

### ISSUE THREAD

**Issue by bdon** [OCHA-DAP/hdx-python-api#8] opened 2017-04-12 03:59 UTC
```
File "/usr/local/lib/python2.7/dist-packages/hdx/data/hdxobject.py", line 289, in _save_to_hdx
result = self._write_to_hdx(action, self.data, id_field_name, file_to_upload)
File "/usr/local/lib/python2.7/dist-packages/hdx/data/hdxobject.py", line 271, in _write_to_hdx
six.raise_from(HDXError('Failed when trying to %s %s! (POST)' % (action, self.data[id_field_name])), e)
File "/usr/local/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
HDXError: Failed when trying to update 1d55221a-5fda-459c-9295-54185f392e81! (POST)
```

When invalid values are POSTed to the CKAN api, it fails this way - the actual CKAN exception has useful information about why the request failed, but they are squelched when caught and re-raised as HDXError

**Comment by mcarans** [comment] 2017-04-12 08:11
I think that in the Python 3 version, the full CKAN exception was displayed. Perhaps there is an option in six to behave similarly?

**Comment by mcarans** [comment] 2017-04-12 08:32
Seems six.raise_from behaves differently on Python 2 to Python 3 :-(
six.raise_from(exc_value, exc_value_from)¶
Raise an exception from a context. On Python 3, this is equivalent to raise exc_value from exc_value_from. On Python 2, which does not support exception chaining, it is equivalent to raise exc_value.

Maybe could use this one:
six.reraise(exc_type, exc_value, exc_traceback=None)
Reraise an exception, possibly with a different traceback. In the simple case, reraise(*sys.exc_info()) with an active exception (in an except block) reraises the current exception with the last traceback. A different traceback can be specified with the exc_traceback parameter. Note that since the exception reraising is done within the reraise() function, Python will attach the call frame of reraise() to whatever traceback is raised.

**Comment by mcarans** [comment] 2017-04-21 13:42
This is fixed in the master branch. I will do a release soon. If you have time to check master before then, please confirm and close the ticket, otherwise I'll let you know when you can test a release

**Comment by mcarans** [comment] 2017-04-24 16:18
HDX Python 1.1.0 on PyPi fixes this. @bdon Please confirm and close.

**Comment by mojodna** [comment] 2017-04-24 19:09
Confirmed, thanks!

**Closed** 2017-04-24 20:05 UTC
